# Generated by Django 3.0.3 on 2020-08-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recomend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=1)),
                ('distance', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('swin_time', models.CharField(max_length=11)),
                ('gender_m', models.IntegerField(default=1)),
                ('stroke_code_bk', models.IntegerField(default=1)),
                ('stroke_code_br', models.IntegerField(default=1)),
                ('stroke_code_fl', models.IntegerField(default=1)),
                ('stroke_code_fr', models.IntegerField(default=1)),
                ('stroke_code_im', models.IntegerField(default=1)),
            ],
        ),
    ]
